modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/andrew0030/SwampierSwamps/issues"
logoFile="logo.png"
license="GNU Lesser General Public License v3.0"

[[mods]]
    modId="swampier_swamps"
    version="1.19.3-2.0.2"
    displayName="Swampier Swamps"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/swampier-swamps"
    credits=""
    authors="andrew0030"
    description='''Swampier Swamps is a Mod that aims to overhaul and improve the Swamp Biome and some of the features added in the Wild Update.'''

[[dependencies.swampier_swamps]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.18,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.swampier_swamps]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"